config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'couriers#index'

  resources :couriers do
    resources :packages
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
# frozen_string_literal: true

class Courier < ApplicationRecord
  has_many :packages, dependent: :destroy
  validates :name, presence: true,
                   length: { minimum: 3 }
  validates :email, presence: true
end

app/models/package.rb
# frozen_string_literal: true

class Package < ApplicationRecord
  belongs_to :courier
  validates :tracking_number, presence: true,
                              length: { in: 10..20 }
  validates :delivery_status, inclusion: [true, false]
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
# frozen_string_literal: true

class CouriersController < ApplicationController
  before_action :set_courier, only: %i[show edit update destroy]

  def index
    @couriers = Courier.all.order('created_at DESC')
  end

  def show; end

  def new
    @courier = Courier.new
  end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to @courier
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @courier.update(courier_params)
      redirect_to @courier
    else
      render 'edit'
    end
  end

  def destroy
    @courier.destroy

    redirect_to couriers_path
  end

  private

  def set_courier
    @courier = Courier.find(params[:id])
  end

  def courier_params
    params.require(:courier).permit(:name, :email)
  end
end

app/controllers/packages_controller.rb
# frozen_string_literal: true

class PackagesController < ApplicationController
  def create
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.create(package_params)
    redirect_to courier_path(@courier)
  end

  def destroy
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.find(params[:id])
    @package.destroy
    redirect_to courier_path(@courier)
  end

  private

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/couriers_helper.rb
# frozen_string_literal: true

module CouriersHelper
end

app/helpers/packages_helper.rb
# frozen_string_literal: true

module PackagesHelper
end

app/views/couriers/_courier.html.erb
<% @couriers.each do |courier| %>
  <tr>
    <td><%= courier.name %></td>
    <td><%= courier.email %></td>
    <td><%= courier.created_at.strftime("%B %d, %Y") %></td>
    <td><%= link_to 'Show', courier_path(courier.id) %></td>
    <td><%= link_to 'Edit', edit_courier_path(courier.id) %></td>
    <td><%= link_to 'Delete', courier_path(courier.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/couriers/_form.html.erb
<h2><%= action_name == 'new' ? 'New' : 'Edit' %>  courier</h2>
<br>
<div class="container">
  <%= form_for @courier do |f| %>
    <div class="col-md-3">
      <%= f.text_field :name, placeholder: "Write name", class: "form-control" %>
    </div>
    <br>
    <div class="col-md-3">
      <%= f.text_field :email, placeholder: "write email", class: "form-control" %>
    </div>
    <br>
    <div class="col-md-3">
      <%= f.submit %>
    </div>
  <% end %>
    <hr>
    <div class="col-md-3"><%= link_to 'Back', couriers_path, class: "btn btn-primary" %></div>
</div>

app/views/couriers/edit.html.erb
<%= render "form" %>

app/views/couriers/index.html.erb
<h1 class="text-center">Couriers</h1>
<div class="container">
  <table class="table table-striped text-center">
    <thead class="thead-dark">
       <tr>
         <th scope="col">Name</th>
         <th scope="col">Email</th>
         <th scope="col">Time</th>
         <th colspan=3 scope="col">Actions</th>
       </tr>
    </thead>
    <tbody>
      <%= render 'courier' %>
    </tbody>
  </table>
  <hr>
</div>

<%= link_to 'Add New Courier', new_courier_path, class: "btn btn-primary" %>

app/views/couriers/new.html.erb
<%= render "form" %>

app/views/couriers/show.html.erb
<div class="container">
  <div class="col-md-9">
    <h2 class="text-center">Courier</h2>
    <table class="table table-striped">
      <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Time</th>
        <th colspan=2 scope="col">Actions</th>

      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @courier.name %></td>
        <td><%= @courier.email %></td>
        <td><%= @courier.created_at.strftime("%B %d, %Y") %></td>
        <td><%= link_to 'Edit', edit_courier_path(@courier.id) %></td>
        <td><%= link_to 'Delete', courier_path(@courier.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="container">
  <div class="col-md-9">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Tracking Number</th>
          <th scope="col">Delivery Status</th>
          <th scope="col">Timing</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
            <%= render @courier.packages %>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="container">
  <div class="col-md-9">
    <%= render 'packages/form' %>
  </div>
</div>
<br>
<%= link_to 'Back', couriers_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>